### ISSUE TITLE
仓库地址貌似不对啊

### ISSUE THREAD

**Issue by fangcaiwen** [bcqq/Android-DragRecyclerView#1]
就是导入第一步一直导不进去，提示版本号不对，是不是地址不对

**Comment by bocq** [comment]
更新了新版本仓库还没有更新。仓库更新后我会告诉你就可以使用了。
你也可以直接用AndroidStudio git下载到你的本地，只使用library部分就可以了。

**Comment by bocq** [comment]
仓库已经更新可以使用了
